
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Contact: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Contact details:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">A shortlist of contact details for the available company contacts.</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>Quick details:</b><br><br>
						Company contacts: 4<br>
						Conversations: 498<br>
						By phone: 383<br>
						By email: 109<br>
						By visitation: 6<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

