
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Finance: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td style="vertical-align: top; width: 400px;" rowspan="2">
						<b>Detailed Financials:</b><br><br>
						First reminders: 3<br>
						Open first reminder invoices: &euro; 342.880,-<br>
						Second reminders: 2<br>
						Open second reminder invoices: &euro; 228.880,-<br>
						Formal summons: 1<br>
						Open formal summon invoices: &euro; 114.880,-<br>
						Open invoices: 1<br>
						Open invoices: &euro; 114.880,-<br>
						Paid invoices: 10<br>
						Paid invoices: &euro; 1.148.800,-<br>
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Open invoices:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Shortlist of invoices (inv id, amount, due day, days late)</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>Quick statistics:</b><br><br>
						First reminders: 3<br>
						Second reminders: 2<br>
						Formal summons: 1<br>
						Open invoices: 1<br>
						Closed invoices: 10<br>
						Company tax rate: 0%<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

