
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Hardware: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td style="vertical-align: top; width: 400px;" rowspan="2">
						<b>Hardware details:</b><br><br>
						Floorspace: 120m2<br>
						Corridors: 2<br>
						Corridor 1 temperature: 21'C<br>
						Corridor 2 temperature: 21'C<br>
						Cabinets: 80<br>
						Max power: 2.5kWh<br>
						Live power usage: 1.75kWh<br>
						Live current: 310A<br>
						Connected PDU's: 5<br>
						PDU 1 Load: 0.2kWh<br>
						PDU 2 Load: 0.5kWh<br>
						PDU 7 Load: 0.3kWh<br>
						PDU 9 Load: 0.5kWh<br>
						PDU 14 Load: 0.25kWh<br>
						Live machines: 540<br>
						Connected APC's: 148<br>
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Open Tickets:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Currently no tickets open.</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>Property statistics:</b><br><br>
						Floorspace: 120m2<br>
						Cabinets: 80<br>
						Max power: 2.5kWh<br>
						Current power use: 1.75kWh<br>
						Live machines: 540<br>
						Connected APC's: 148<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

