
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Sales: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td style="vertical-align: top; width: 400px;" rowspan="2">
						<b>Detailed Statistics:</b><br><br>
						Open quotes: 1<br>
						Potential revenue from open quotes: &euro; 128.000,-<br>
						Closed quotes: 33 (no sale)<br>
						Lost revenue from closed quotes: &euro; 378.500,-<br>
						Accepted quotes: 76<br>
						Revenue from accepted quotes (year): &euro; 1.378.570,-<br>
						Monthly revenue from accepted quotes: &euro; 114.880,-<br>
						
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Current Activities:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Currently no running activities for this customer.</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>Quick information:</b><br><br>
						Account manager: Robin Lim<br>
						Secondary manager: Gregor Snip<br>
						Open quotes: 1<br>
						Closed quotes: 33 (no sale)<br>
						Accepted quotes: 76<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

