
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Visits and Shipments: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td style="vertical-align: top; width: 450px;" rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Shipments:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Shortlist of shipments.</td>
							</tr>
						</table>
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Access requests:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Shortlist of requests.</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>DC statistics:</b><br><br>
						Open access requests: 3<br>
						Current visitors: 2<br>
						Closed access requests: 898<br>
						No show requests: 102<br>
						Shipments registered: 405<br>
						Shipments received: 403<br>
						Open Shipments: 4<br>
						Shipments picked up: 401<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

