<?php 
$mysql_server="localhost";
$mysql_user="change_me";
$mysql_password="change_me";
$mysql_db_xzdr="xzdr";
$mysql_tb_recoveries="releases";
$mysql_tb_files="files";
$mysql_tb_accounts="accounts";
?>
