
<table style="width: 100%; height: 100%; margin: 0px 30px;">
	<tr>
		<th style="height: 30px; text-align: center;">
			<h2>Overview: FDC Server</h2>
		</th>
	</tr>
	<tr>
		<td>
			<table style="width: 100%; height: 100%;">
				<tr>
					<td style="vertical-align: top; width: 300px;">
						<b>Company details:</b><br><br>
						FDC Server<br>
						Somestreet 1000<br>
						90210 ZIP<br>
						Somecity<br>
						SomeCountry<br>
					</td>
					<td style="vertical-align: top; width: 300px;">
						<b>Financial statistics:</b><br><br>
						First reminders: 3<br>
						Second reminders: 2<br>
						Formal summons: 1<br>
						Open invoices: 1<br>
						Closed invoices: 10<br>
					</td>
					<td style="vertical-align: top; width: 300px;">
						<b>Sales statistics:</b><br><br>
						Account manager: Robin Lim<br>
						Secondary manager: Gregor Snip<br>
						Open quotes: 1<br>
						Closed quotes: 33 (no sale)<br>
						Accepted quotes: 76<br>
					</td>
					<td rowspan="2">
						<table style="width: 100%; height: 100%; vertical-align: top;">
							<tr>
								<th style="height: 30px; vertical-align: top; font-weight: bold;">Open Tickets:</th>
							</tr>
							<tr>
								<td style="vertical-align: top;">Currently no tickets open.</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="vertical-align: top;">
						<b>Property statistics:</b><br><br>
						Floorspace: 120m2<br>
						Cabinets: 80<br>
						Max power: 2.5kWh<br>
						Current power use: 1.75kWh<br>
						Live machines: 540<br>
						Connected APC's: 148<br>
					</td>
					<td style="vertical-align: top;">
						<b>DC statistics:</b><br><br>
						Open access requests: 3<br>
						Current visitors: 2<br>
						Closed access requests: 898<br>
						No show requests: 102<br>
						Shipments registered: 405<br>
						Shipments received: 403<br>
						Open Shipments: 4<br>
						Shipments picked up: 401<br>
					</td>
					<td style="vertical-align: top;">
						<b>Support Statistics:</b><br><br>
						Closed tickets: 303<br>
						Hands on requests: 24<br>
						High priority tickets: 13<br>
						Medium priority tickets: 90<br>
						Low priority tickets: 200<br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

